a= input("a= ")
b= input("b= ")
a=int(a)
b=int(b)
print("The addition of the numbers=",int(a)+int(b))
print("The subtraction of the numbers=",a-b)
print("The division of the numbers=",a%b)
print("The multiplication of the numbers=",a*b)
print("The mode of the numbers=",a/b)
print("Thank you for choosing this calculator!")