# tup=(1,2,3,4,5,5)
# print(type(tup))
# print(tup)
# print(tup[0])
# print(tup[1])
# print(tup[2])
# print(tup[3])
# print(tup[4])

# countries = ("spain", "italy", "india", "england", "germany")
# temp = list(countries)
# temp.append("russia")
# temp.pop(3)
# temp[2] = ("finland")
# countries = tuple(temp)
# print(countries)

tuple1 = (0, 1, 2, 3, 2, 3, 1, 3, 2, 3)
# res = tuple1.count(2)
# res = tuple1.index(3)
# res = tuple1.index(3,4,8)
res = len(tuple1) 
print("count of 3 in tuple is:", res)